//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JADEG.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkDungeonTile
    {
        public int Id { get; set; }
        public int FK_Tile { get; set; }
        public int FK_Dungeon { get; set; }
        public int XCoord { get; set; }
        public int YCoord { get; set; }
    
        public virtual Dungeon Dungeon { get; set; }
        public virtual Tile Tile { get; set; }
    }
}
