//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JADEG.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public Nullable<int> FK_LinkDungeonTile { get; set; }
        public string Name { get; set; }
        public string Skin { get; set; }
    
        public virtual LinkDungeonTile LinkDungeonTile { get; set; }
    }
}
